//
//  SampleData.swift
//  GithubSearchUserTests
//
//  Created by Jinho Jang on 2020/10/19.
//

struct SampleData {
    static let userList = """
    {
        "total_count": 532312,
        "incomplete_results": false,
        "items": [
            {
                "login": "A",
                "id": 1410106,
                "node_id": "MDQ6VXNlcjE0MTAxMDY=",
                "avatar_url": "https://avatars2.githubusercontent.com/u/1410106?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/A",
                "html_url": "https://github.com/A",
                "followers_url": "https://api.github.com/users/A/followers",
                "following_url": "https://api.github.com/users/A/following{/other_user}",
                "gists_url": "https://api.github.com/users/A/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/A/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/A/subscriptions",
                "organizations_url": "https://api.github.com/users/A/orgs",
                "repos_url": "https://api.github.com/users/A/repos",
                "events_url": "https://api.github.com/users/A/events{/privacy}",
                "received_events_url": "https://api.github.com/users/A/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "Au-2020",
                "id": 44748278,
                "node_id": "MDQ6VXNlcjQ0NzQ4Mjc4",
                "avatar_url": "https://avatars1.githubusercontent.com/u/44748278?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Au-2020",
                "html_url": "https://github.com/Au-2020",
                "followers_url": "https://api.github.com/users/Au-2020/followers",
                "following_url": "https://api.github.com/users/Au-2020/following{/other_user}",
                "gists_url": "https://api.github.com/users/Au-2020/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Au-2020/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Au-2020/subscriptions",
                "organizations_url": "https://api.github.com/users/Au-2020/orgs",
                "repos_url": "https://api.github.com/users/Au-2020/repos",
                "events_url": "https://api.github.com/users/Au-2020/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Au-2020/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "snyff",
                "id": 45491,
                "node_id": "MDQ6VXNlcjQ1NDkx",
                "avatar_url": "https://avatars1.githubusercontent.com/u/45491?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/snyff",
                "html_url": "https://github.com/snyff",
                "followers_url": "https://api.github.com/users/snyff/followers",
                "following_url": "https://api.github.com/users/snyff/following{/other_user}",
                "gists_url": "https://api.github.com/users/snyff/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/snyff/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/snyff/subscriptions",
                "organizations_url": "https://api.github.com/users/snyff/orgs",
                "repos_url": "https://api.github.com/users/snyff/repos",
                "events_url": "https://api.github.com/users/snyff/events{/privacy}",
                "received_events_url": "https://api.github.com/users/snyff/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "Amichai",
                "id": 313874,
                "node_id": "MDQ6VXNlcjMxMzg3NA==",
                "avatar_url": "https://avatars3.githubusercontent.com/u/313874?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Amichai",
                "html_url": "https://github.com/Amichai",
                "followers_url": "https://api.github.com/users/Amichai/followers",
                "following_url": "https://api.github.com/users/Amichai/following{/other_user}",
                "gists_url": "https://api.github.com/users/Amichai/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Amichai/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Amichai/subscriptions",
                "organizations_url": "https://api.github.com/users/Amichai/orgs",
                "repos_url": "https://api.github.com/users/Amichai/repos",
                "events_url": "https://api.github.com/users/Amichai/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Amichai/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "adamwiggins",
                "id": 177,
                "node_id": "MDQ6VXNlcjE3Nw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/177?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/adamwiggins",
                "html_url": "https://github.com/adamwiggins",
                "followers_url": "https://api.github.com/users/adamwiggins/followers",
                "following_url": "https://api.github.com/users/adamwiggins/following{/other_user}",
                "gists_url": "https://api.github.com/users/adamwiggins/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/adamwiggins/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/adamwiggins/subscriptions",
                "organizations_url": "https://api.github.com/users/adamwiggins/orgs",
                "repos_url": "https://api.github.com/users/adamwiggins/repos",
                "events_url": "https://api.github.com/users/adamwiggins/events{/privacy}",
                "received_events_url": "https://api.github.com/users/adamwiggins/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "adulau",
                "id": 3309,
                "node_id": "MDQ6VXNlcjMzMDk=",
                "avatar_url": "https://avatars2.githubusercontent.com/u/3309?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/adulau",
                "html_url": "https://github.com/adulau",
                "followers_url": "https://api.github.com/users/adulau/followers",
                "following_url": "https://api.github.com/users/adulau/following{/other_user}",
                "gists_url": "https://api.github.com/users/adulau/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/adulau/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/adulau/subscriptions",
                "organizations_url": "https://api.github.com/users/adulau/orgs",
                "repos_url": "https://api.github.com/users/adulau/repos",
                "events_url": "https://api.github.com/users/adulau/events{/privacy}",
                "received_events_url": "https://api.github.com/users/adulau/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "iptodays",
                "id": 15830996,
                "node_id": "MDQ6VXNlcjE1ODMwOTk2",
                "avatar_url": "https://avatars3.githubusercontent.com/u/15830996?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/iptodays",
                "html_url": "https://github.com/iptodays",
                "followers_url": "https://api.github.com/users/iptodays/followers",
                "following_url": "https://api.github.com/users/iptodays/following{/other_user}",
                "gists_url": "https://api.github.com/users/iptodays/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/iptodays/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/iptodays/subscriptions",
                "organizations_url": "https://api.github.com/users/iptodays/orgs",
                "repos_url": "https://api.github.com/users/iptodays/repos",
                "events_url": "https://api.github.com/users/iptodays/events{/privacy}",
                "received_events_url": "https://api.github.com/users/iptodays/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "ngs",
                "id": 18631,
                "node_id": "MDQ6VXNlcjE4NjMx",
                "avatar_url": "https://avatars0.githubusercontent.com/u/18631?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ngs",
                "html_url": "https://github.com/ngs",
                "followers_url": "https://api.github.com/users/ngs/followers",
                "following_url": "https://api.github.com/users/ngs/following{/other_user}",
                "gists_url": "https://api.github.com/users/ngs/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ngs/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ngs/subscriptions",
                "organizations_url": "https://api.github.com/users/ngs/orgs",
                "repos_url": "https://api.github.com/users/ngs/repos",
                "events_url": "https://api.github.com/users/ngs/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ngs/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "aarizaq",
                "id": 62071,
                "node_id": "MDQ6VXNlcjYyMDcx",
                "avatar_url": "https://avatars1.githubusercontent.com/u/62071?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/aarizaq",
                "html_url": "https://github.com/aarizaq",
                "followers_url": "https://api.github.com/users/aarizaq/followers",
                "following_url": "https://api.github.com/users/aarizaq/following{/other_user}",
                "gists_url": "https://api.github.com/users/aarizaq/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/aarizaq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/aarizaq/subscriptions",
                "organizations_url": "https://api.github.com/users/aarizaq/orgs",
                "repos_url": "https://api.github.com/users/aarizaq/repos",
                "events_url": "https://api.github.com/users/aarizaq/events{/privacy}",
                "received_events_url": "https://api.github.com/users/aarizaq/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "alsayadii",
                "id": 1955591,
                "node_id": "MDQ6VXNlcjE5NTU1OTE=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1955591?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/alsayadii",
                "html_url": "https://github.com/alsayadii",
                "followers_url": "https://api.github.com/users/alsayadii/followers",
                "following_url": "https://api.github.com/users/alsayadii/following{/other_user}",
                "gists_url": "https://api.github.com/users/alsayadii/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/alsayadii/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/alsayadii/subscriptions",
                "organizations_url": "https://api.github.com/users/alsayadii/orgs",
                "repos_url": "https://api.github.com/users/alsayadii/repos",
                "events_url": "https://api.github.com/users/alsayadii/events{/privacy}",
                "received_events_url": "https://api.github.com/users/alsayadii/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "xxczaki",
                "id": 22645979,
                "node_id": "MDQ6VXNlcjIyNjQ1OTc5",
                "avatar_url": "https://avatars3.githubusercontent.com/u/22645979?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/xxczaki",
                "html_url": "https://github.com/xxczaki",
                "followers_url": "https://api.github.com/users/xxczaki/followers",
                "following_url": "https://api.github.com/users/xxczaki/following{/other_user}",
                "gists_url": "https://api.github.com/users/xxczaki/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/xxczaki/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/xxczaki/subscriptions",
                "organizations_url": "https://api.github.com/users/xxczaki/orgs",
                "repos_url": "https://api.github.com/users/xxczaki/repos",
                "events_url": "https://api.github.com/users/xxczaki/events{/privacy}",
                "received_events_url": "https://api.github.com/users/xxczaki/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "tuzimoe",
                "id": 17731805,
                "node_id": "MDQ6VXNlcjE3NzMxODA1",
                "avatar_url": "https://avatars1.githubusercontent.com/u/17731805?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/tuzimoe",
                "html_url": "https://github.com/tuzimoe",
                "followers_url": "https://api.github.com/users/tuzimoe/followers",
                "following_url": "https://api.github.com/users/tuzimoe/following{/other_user}",
                "gists_url": "https://api.github.com/users/tuzimoe/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/tuzimoe/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tuzimoe/subscriptions",
                "organizations_url": "https://api.github.com/users/tuzimoe/orgs",
                "repos_url": "https://api.github.com/users/tuzimoe/repos",
                "events_url": "https://api.github.com/users/tuzimoe/events{/privacy}",
                "received_events_url": "https://api.github.com/users/tuzimoe/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "yi-ge",
                "id": 6657330,
                "node_id": "MDQ6VXNlcjY2NTczMzA=",
                "avatar_url": "https://avatars2.githubusercontent.com/u/6657330?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/yi-ge",
                "html_url": "https://github.com/yi-ge",
                "followers_url": "https://api.github.com/users/yi-ge/followers",
                "following_url": "https://api.github.com/users/yi-ge/following{/other_user}",
                "gists_url": "https://api.github.com/users/yi-ge/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/yi-ge/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/yi-ge/subscriptions",
                "organizations_url": "https://api.github.com/users/yi-ge/orgs",
                "repos_url": "https://api.github.com/users/yi-ge/repos",
                "events_url": "https://api.github.com/users/yi-ge/events{/privacy}",
                "received_events_url": "https://api.github.com/users/yi-ge/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "AHXR",
                "id": 27564220,
                "node_id": "MDQ6VXNlcjI3NTY0MjIw",
                "avatar_url": "https://avatars2.githubusercontent.com/u/27564220?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/AHXR",
                "html_url": "https://github.com/AHXR",
                "followers_url": "https://api.github.com/users/AHXR/followers",
                "following_url": "https://api.github.com/users/AHXR/following{/other_user}",
                "gists_url": "https://api.github.com/users/AHXR/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/AHXR/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/AHXR/subscriptions",
                "organizations_url": "https://api.github.com/users/AHXR/orgs",
                "repos_url": "https://api.github.com/users/AHXR/repos",
                "events_url": "https://api.github.com/users/AHXR/events{/privacy}",
                "received_events_url": "https://api.github.com/users/AHXR/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "outsideris",
                "id": 390146,
                "node_id": "MDQ6VXNlcjM5MDE0Ng==",
                "avatar_url": "https://avatars1.githubusercontent.com/u/390146?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/outsideris",
                "html_url": "https://github.com/outsideris",
                "followers_url": "https://api.github.com/users/outsideris/followers",
                "following_url": "https://api.github.com/users/outsideris/following{/other_user}",
                "gists_url": "https://api.github.com/users/outsideris/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/outsideris/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/outsideris/subscriptions",
                "organizations_url": "https://api.github.com/users/outsideris/orgs",
                "repos_url": "https://api.github.com/users/outsideris/repos",
                "events_url": "https://api.github.com/users/outsideris/events{/privacy}",
                "received_events_url": "https://api.github.com/users/outsideris/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "joshhartigan",
                "id": 5961708,
                "node_id": "MDQ6VXNlcjU5NjE3MDg=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/5961708?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/joshhartigan",
                "html_url": "https://github.com/joshhartigan",
                "followers_url": "https://api.github.com/users/joshhartigan/followers",
                "following_url": "https://api.github.com/users/joshhartigan/following{/other_user}",
                "gists_url": "https://api.github.com/users/joshhartigan/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/joshhartigan/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/joshhartigan/subscriptions",
                "organizations_url": "https://api.github.com/users/joshhartigan/orgs",
                "repos_url": "https://api.github.com/users/joshhartigan/repos",
                "events_url": "https://api.github.com/users/joshhartigan/events{/privacy}",
                "received_events_url": "https://api.github.com/users/joshhartigan/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "prodigeni",
                "id": 1476070,
                "node_id": "MDQ6VXNlcjE0NzYwNzA=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/1476070?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/prodigeni",
                "html_url": "https://github.com/prodigeni",
                "followers_url": "https://api.github.com/users/prodigeni/followers",
                "following_url": "https://api.github.com/users/prodigeni/following{/other_user}",
                "gists_url": "https://api.github.com/users/prodigeni/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/prodigeni/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/prodigeni/subscriptions",
                "organizations_url": "https://api.github.com/users/prodigeni/orgs",
                "repos_url": "https://api.github.com/users/prodigeni/repos",
                "events_url": "https://api.github.com/users/prodigeni/events{/privacy}",
                "received_events_url": "https://api.github.com/users/prodigeni/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "ufoym",
                "id": 2270240,
                "node_id": "MDQ6VXNlcjIyNzAyNDA=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/2270240?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ufoym",
                "html_url": "https://github.com/ufoym",
                "followers_url": "https://api.github.com/users/ufoym/followers",
                "following_url": "https://api.github.com/users/ufoym/following{/other_user}",
                "gists_url": "https://api.github.com/users/ufoym/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ufoym/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ufoym/subscriptions",
                "organizations_url": "https://api.github.com/users/ufoym/orgs",
                "repos_url": "https://api.github.com/users/ufoym/repos",
                "events_url": "https://api.github.com/users/ufoym/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ufoym/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "kkmonlee",
                "id": 6388711,
                "node_id": "MDQ6VXNlcjYzODg3MTE=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/6388711?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/kkmonlee",
                "html_url": "https://github.com/kkmonlee",
                "followers_url": "https://api.github.com/users/kkmonlee/followers",
                "following_url": "https://api.github.com/users/kkmonlee/following{/other_user}",
                "gists_url": "https://api.github.com/users/kkmonlee/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/kkmonlee/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kkmonlee/subscriptions",
                "organizations_url": "https://api.github.com/users/kkmonlee/orgs",
                "repos_url": "https://api.github.com/users/kkmonlee/repos",
                "events_url": "https://api.github.com/users/kkmonlee/events{/privacy}",
                "received_events_url": "https://api.github.com/users/kkmonlee/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            },
            {
                "login": "carsonoid",
                "id": 2973513,
                "node_id": "MDQ6VXNlcjI5NzM1MTM=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/2973513?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/carsonoid",
                "html_url": "https://github.com/carsonoid",
                "followers_url": "https://api.github.com/users/carsonoid/followers",
                "following_url": "https://api.github.com/users/carsonoid/following{/other_user}",
                "gists_url": "https://api.github.com/users/carsonoid/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/carsonoid/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/carsonoid/subscriptions",
                "organizations_url": "https://api.github.com/users/carsonoid/orgs",
                "repos_url": "https://api.github.com/users/carsonoid/repos",
                "events_url": "https://api.github.com/users/carsonoid/events{/privacy}",
                "received_events_url": "https://api.github.com/users/carsonoid/received_events",
                "type": "User",
                "site_admin": false,
                "score": 1.0
            }
        ]
    }
    """
    
    static let repo = """
    {
      "login": "A",
      "id": 1410106,
      "node_id": "MDQ6VXNlcjE0MTAxMDY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1410106?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/A",
      "html_url": "https://github.com/A",
      "followers_url": "https://api.github.com/users/A/followers",
      "following_url": "https://api.github.com/users/A/following{/other_user}",
      "gists_url": "https://api.github.com/users/A/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/A/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/A/subscriptions",
      "organizations_url": "https://api.github.com/users/A/orgs",
      "repos_url": "https://api.github.com/users/A/repos",
      "events_url": "https://api.github.com/users/A/events{/privacy}",
      "received_events_url": "https://api.github.com/users/A/received_events",
      "type": "User",
      "site_admin": false,
      "name": "Shuvalov Anton",
      "company": "@winstrike",
      "blog": "http://shuvalov.info",
      "location": "Ho Chi Minh, Vietnam",
      "email": null,
      "hireable": null,
      "bio": null,
      "twitter_username": null,
      "public_repos": 45,
      "public_gists": 128,
      "followers": 422,
      "following": 123,
      "created_at": "2012-02-05T14:53:26Z",
      "updated_at": "2020-10-17T04:47:24Z"
    }
    """
}
