//
//  SampleData.swift
//  GithubSearchUserTests
//
//  Created by Jinho Jang on 2020/10/19.
//

struct SampleData {
    static let userList = """
    {
      "total_count": 488614,
      "incomplete_results": false,
      "items": [
        {
          "login": "A",
          "id": 1410106,
          "node_id": "MDQ6VXNlcjE0MTAxMDY=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/1410106?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/A",
          "html_url": "https://github.com/A",
          "followers_url": "https://api.github.com/users/A/followers",
          "following_url": "https://api.github.com/users/A/following{/other_user}",
          "gists_url": "https://api.github.com/users/A/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/A/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/A/subscriptions",
          "organizations_url": "https://api.github.com/users/A/orgs",
          "repos_url": "https://api.github.com/users/A/repos",
          "events_url": "https://api.github.com/users/A/events{/privacy}",
          "received_events_url": "https://api.github.com/users/A/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "snyff",
          "id": 45491,
          "node_id": "MDQ6VXNlcjQ1NDkx",
          "avatar_url": "https://avatars1.githubusercontent.com/u/45491?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/snyff",
          "html_url": "https://github.com/snyff",
          "followers_url": "https://api.github.com/users/snyff/followers",
          "following_url": "https://api.github.com/users/snyff/following{/other_user}",
          "gists_url": "https://api.github.com/users/snyff/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/snyff/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/snyff/subscriptions",
          "organizations_url": "https://api.github.com/users/snyff/orgs",
          "repos_url": "https://api.github.com/users/snyff/repos",
          "events_url": "https://api.github.com/users/snyff/events{/privacy}",
          "received_events_url": "https://api.github.com/users/snyff/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "adamwiggins",
          "id": 177,
          "node_id": "MDQ6VXNlcjE3Nw==",
          "avatar_url": "https://avatars0.githubusercontent.com/u/177?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/adamwiggins",
          "html_url": "https://github.com/adamwiggins",
          "followers_url": "https://api.github.com/users/adamwiggins/followers",
          "following_url": "https://api.github.com/users/adamwiggins/following{/other_user}",
          "gists_url": "https://api.github.com/users/adamwiggins/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/adamwiggins/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/adamwiggins/subscriptions",
          "organizations_url": "https://api.github.com/users/adamwiggins/orgs",
          "repos_url": "https://api.github.com/users/adamwiggins/repos",
          "events_url": "https://api.github.com/users/adamwiggins/events{/privacy}",
          "received_events_url": "https://api.github.com/users/adamwiggins/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "Amichai",
          "id": 313874,
          "node_id": "MDQ6VXNlcjMxMzg3NA==",
          "avatar_url": "https://avatars3.githubusercontent.com/u/313874?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Amichai",
          "html_url": "https://github.com/Amichai",
          "followers_url": "https://api.github.com/users/Amichai/followers",
          "following_url": "https://api.github.com/users/Amichai/following{/other_user}",
          "gists_url": "https://api.github.com/users/Amichai/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Amichai/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Amichai/subscriptions",
          "organizations_url": "https://api.github.com/users/Amichai/orgs",
          "repos_url": "https://api.github.com/users/Amichai/repos",
          "events_url": "https://api.github.com/users/Amichai/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Amichai/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "adulau",
          "id": 3309,
          "node_id": "MDQ6VXNlcjMzMDk=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/3309?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/adulau",
          "html_url": "https://github.com/adulau",
          "followers_url": "https://api.github.com/users/adulau/followers",
          "following_url": "https://api.github.com/users/adulau/following{/other_user}",
          "gists_url": "https://api.github.com/users/adulau/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/adulau/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/adulau/subscriptions",
          "organizations_url": "https://api.github.com/users/adulau/orgs",
          "repos_url": "https://api.github.com/users/adulau/repos",
          "events_url": "https://api.github.com/users/adulau/events{/privacy}",
          "received_events_url": "https://api.github.com/users/adulau/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "A-ee",
          "id": 43641740,
          "node_id": "MDQ6VXNlcjQzNjQxNzQw",
          "avatar_url": "https://avatars3.githubusercontent.com/u/43641740?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/A-ee",
          "html_url": "https://github.com/A-ee",
          "followers_url": "https://api.github.com/users/A-ee/followers",
          "following_url": "https://api.github.com/users/A-ee/following{/other_user}",
          "gists_url": "https://api.github.com/users/A-ee/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/A-ee/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/A-ee/subscriptions",
          "organizations_url": "https://api.github.com/users/A-ee/orgs",
          "repos_url": "https://api.github.com/users/A-ee/repos",
          "events_url": "https://api.github.com/users/A-ee/events{/privacy}",
          "received_events_url": "https://api.github.com/users/A-ee/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "ngs",
          "id": 18631,
          "node_id": "MDQ6VXNlcjE4NjMx",
          "avatar_url": "https://avatars0.githubusercontent.com/u/18631?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/ngs",
          "html_url": "https://github.com/ngs",
          "followers_url": "https://api.github.com/users/ngs/followers",
          "following_url": "https://api.github.com/users/ngs/following{/other_user}",
          "gists_url": "https://api.github.com/users/ngs/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/ngs/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/ngs/subscriptions",
          "organizations_url": "https://api.github.com/users/ngs/orgs",
          "repos_url": "https://api.github.com/users/ngs/repos",
          "events_url": "https://api.github.com/users/ngs/events{/privacy}",
          "received_events_url": "https://api.github.com/users/ngs/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "aarizaq",
          "id": 62071,
          "node_id": "MDQ6VXNlcjYyMDcx",
          "avatar_url": "https://avatars1.githubusercontent.com/u/62071?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/aarizaq",
          "html_url": "https://github.com/aarizaq",
          "followers_url": "https://api.github.com/users/aarizaq/followers",
          "following_url": "https://api.github.com/users/aarizaq/following{/other_user}",
          "gists_url": "https://api.github.com/users/aarizaq/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/aarizaq/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/aarizaq/subscriptions",
          "organizations_url": "https://api.github.com/users/aarizaq/orgs",
          "repos_url": "https://api.github.com/users/aarizaq/repos",
          "events_url": "https://api.github.com/users/aarizaq/events{/privacy}",
          "received_events_url": "https://api.github.com/users/aarizaq/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "iptodays",
          "id": 15830996,
          "node_id": "MDQ6VXNlcjE1ODMwOTk2",
          "avatar_url": "https://avatars3.githubusercontent.com/u/15830996?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/iptodays",
          "html_url": "https://github.com/iptodays",
          "followers_url": "https://api.github.com/users/iptodays/followers",
          "following_url": "https://api.github.com/users/iptodays/following{/other_user}",
          "gists_url": "https://api.github.com/users/iptodays/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/iptodays/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/iptodays/subscriptions",
          "organizations_url": "https://api.github.com/users/iptodays/orgs",
          "repos_url": "https://api.github.com/users/iptodays/repos",
          "events_url": "https://api.github.com/users/iptodays/events{/privacy}",
          "received_events_url": "https://api.github.com/users/iptodays/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "CasterWx",
          "id": 30624750,
          "node_id": "MDQ6VXNlcjMwNjI0NzUw",
          "avatar_url": "https://avatars2.githubusercontent.com/u/30624750?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/CasterWx",
          "html_url": "https://github.com/CasterWx",
          "followers_url": "https://api.github.com/users/CasterWx/followers",
          "following_url": "https://api.github.com/users/CasterWx/following{/other_user}",
          "gists_url": "https://api.github.com/users/CasterWx/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/CasterWx/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/CasterWx/subscriptions",
          "organizations_url": "https://api.github.com/users/CasterWx/orgs",
          "repos_url": "https://api.github.com/users/CasterWx/repos",
          "events_url": "https://api.github.com/users/CasterWx/events{/privacy}",
          "received_events_url": "https://api.github.com/users/CasterWx/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "alsayadii",
          "id": 1955591,
          "node_id": "MDQ6VXNlcjE5NTU1OTE=",
          "avatar_url": "https://avatars1.githubusercontent.com/u/1955591?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/alsayadii",
          "html_url": "https://github.com/alsayadii",
          "followers_url": "https://api.github.com/users/alsayadii/followers",
          "following_url": "https://api.github.com/users/alsayadii/following{/other_user}",
          "gists_url": "https://api.github.com/users/alsayadii/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/alsayadii/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/alsayadii/subscriptions",
          "organizations_url": "https://api.github.com/users/alsayadii/orgs",
          "repos_url": "https://api.github.com/users/alsayadii/repos",
          "events_url": "https://api.github.com/users/alsayadii/events{/privacy}",
          "received_events_url": "https://api.github.com/users/alsayadii/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "xxczaki",
          "id": 22645979,
          "node_id": "MDQ6VXNlcjIyNjQ1OTc5",
          "avatar_url": "https://avatars3.githubusercontent.com/u/22645979?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/xxczaki",
          "html_url": "https://github.com/xxczaki",
          "followers_url": "https://api.github.com/users/xxczaki/followers",
          "following_url": "https://api.github.com/users/xxczaki/following{/other_user}",
          "gists_url": "https://api.github.com/users/xxczaki/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/xxczaki/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/xxczaki/subscriptions",
          "organizations_url": "https://api.github.com/users/xxczaki/orgs",
          "repos_url": "https://api.github.com/users/xxczaki/repos",
          "events_url": "https://api.github.com/users/xxczaki/events{/privacy}",
          "received_events_url": "https://api.github.com/users/xxczaki/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "yi-ge",
          "id": 6657330,
          "node_id": "MDQ6VXNlcjY2NTczMzA=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/6657330?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/yi-ge",
          "html_url": "https://github.com/yi-ge",
          "followers_url": "https://api.github.com/users/yi-ge/followers",
          "following_url": "https://api.github.com/users/yi-ge/following{/other_user}",
          "gists_url": "https://api.github.com/users/yi-ge/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/yi-ge/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/yi-ge/subscriptions",
          "organizations_url": "https://api.github.com/users/yi-ge/orgs",
          "repos_url": "https://api.github.com/users/yi-ge/repos",
          "events_url": "https://api.github.com/users/yi-ge/events{/privacy}",
          "received_events_url": "https://api.github.com/users/yi-ge/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "tuzimoe",
          "id": 17731805,
          "node_id": "MDQ6VXNlcjE3NzMxODA1",
          "avatar_url": "https://avatars1.githubusercontent.com/u/17731805?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/tuzimoe",
          "html_url": "https://github.com/tuzimoe",
          "followers_url": "https://api.github.com/users/tuzimoe/followers",
          "following_url": "https://api.github.com/users/tuzimoe/following{/other_user}",
          "gists_url": "https://api.github.com/users/tuzimoe/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/tuzimoe/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/tuzimoe/subscriptions",
          "organizations_url": "https://api.github.com/users/tuzimoe/orgs",
          "repos_url": "https://api.github.com/users/tuzimoe/repos",
          "events_url": "https://api.github.com/users/tuzimoe/events{/privacy}",
          "received_events_url": "https://api.github.com/users/tuzimoe/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "AHXR",
          "id": 27564220,
          "node_id": "MDQ6VXNlcjI3NTY0MjIw",
          "avatar_url": "https://avatars2.githubusercontent.com/u/27564220?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/AHXR",
          "html_url": "https://github.com/AHXR",
          "followers_url": "https://api.github.com/users/AHXR/followers",
          "following_url": "https://api.github.com/users/AHXR/following{/other_user}",
          "gists_url": "https://api.github.com/users/AHXR/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/AHXR/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/AHXR/subscriptions",
          "organizations_url": "https://api.github.com/users/AHXR/orgs",
          "repos_url": "https://api.github.com/users/AHXR/repos",
          "events_url": "https://api.github.com/users/AHXR/events{/privacy}",
          "received_events_url": "https://api.github.com/users/AHXR/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "joshhartigan",
          "id": 5961708,
          "node_id": "MDQ6VXNlcjU5NjE3MDg=",
          "avatar_url": "https://avatars0.githubusercontent.com/u/5961708?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/joshhartigan",
          "html_url": "https://github.com/joshhartigan",
          "followers_url": "https://api.github.com/users/joshhartigan/followers",
          "following_url": "https://api.github.com/users/joshhartigan/following{/other_user}",
          "gists_url": "https://api.github.com/users/joshhartigan/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/joshhartigan/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/joshhartigan/subscriptions",
          "organizations_url": "https://api.github.com/users/joshhartigan/orgs",
          "repos_url": "https://api.github.com/users/joshhartigan/repos",
          "events_url": "https://api.github.com/users/joshhartigan/events{/privacy}",
          "received_events_url": "https://api.github.com/users/joshhartigan/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "outsideris",
          "id": 390146,
          "node_id": "MDQ6VXNlcjM5MDE0Ng==",
          "avatar_url": "https://avatars1.githubusercontent.com/u/390146?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/outsideris",
          "html_url": "https://github.com/outsideris",
          "followers_url": "https://api.github.com/users/outsideris/followers",
          "following_url": "https://api.github.com/users/outsideris/following{/other_user}",
          "gists_url": "https://api.github.com/users/outsideris/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/outsideris/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/outsideris/subscriptions",
          "organizations_url": "https://api.github.com/users/outsideris/orgs",
          "repos_url": "https://api.github.com/users/outsideris/repos",
          "events_url": "https://api.github.com/users/outsideris/events{/privacy}",
          "received_events_url": "https://api.github.com/users/outsideris/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "prodigeni",
          "id": 1476070,
          "node_id": "MDQ6VXNlcjE0NzYwNzA=",
          "avatar_url": "https://avatars3.githubusercontent.com/u/1476070?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/prodigeni",
          "html_url": "https://github.com/prodigeni",
          "followers_url": "https://api.github.com/users/prodigeni/followers",
          "following_url": "https://api.github.com/users/prodigeni/following{/other_user}",
          "gists_url": "https://api.github.com/users/prodigeni/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/prodigeni/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/prodigeni/subscriptions",
          "organizations_url": "https://api.github.com/users/prodigeni/orgs",
          "repos_url": "https://api.github.com/users/prodigeni/repos",
          "events_url": "https://api.github.com/users/prodigeni/events{/privacy}",
          "received_events_url": "https://api.github.com/users/prodigeni/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "kkmonlee",
          "id": 6388711,
          "node_id": "MDQ6VXNlcjYzODg3MTE=",
          "avatar_url": "https://avatars1.githubusercontent.com/u/6388711?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/kkmonlee",
          "html_url": "https://github.com/kkmonlee",
          "followers_url": "https://api.github.com/users/kkmonlee/followers",
          "following_url": "https://api.github.com/users/kkmonlee/following{/other_user}",
          "gists_url": "https://api.github.com/users/kkmonlee/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/kkmonlee/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/kkmonlee/subscriptions",
          "organizations_url": "https://api.github.com/users/kkmonlee/orgs",
          "repos_url": "https://api.github.com/users/kkmonlee/repos",
          "events_url": "https://api.github.com/users/kkmonlee/events{/privacy}",
          "received_events_url": "https://api.github.com/users/kkmonlee/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "ufoym",
          "id": 2270240,
          "node_id": "MDQ6VXNlcjIyNzAyNDA=",
          "avatar_url": "https://avatars1.githubusercontent.com/u/2270240?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/ufoym",
          "html_url": "https://github.com/ufoym",
          "followers_url": "https://api.github.com/users/ufoym/followers",
          "following_url": "https://api.github.com/users/ufoym/following{/other_user}",
          "gists_url": "https://api.github.com/users/ufoym/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/ufoym/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/ufoym/subscriptions",
          "organizations_url": "https://api.github.com/users/ufoym/orgs",
          "repos_url": "https://api.github.com/users/ufoym/repos",
          "events_url": "https://api.github.com/users/ufoym/events{/privacy}",
          "received_events_url": "https://api.github.com/users/ufoym/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "carsonoid",
          "id": 2973513,
          "node_id": "MDQ6VXNlcjI5NzM1MTM=",
          "avatar_url": "https://avatars0.githubusercontent.com/u/2973513?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/carsonoid",
          "html_url": "https://github.com/carsonoid",
          "followers_url": "https://api.github.com/users/carsonoid/followers",
          "following_url": "https://api.github.com/users/carsonoid/following{/other_user}",
          "gists_url": "https://api.github.com/users/carsonoid/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/carsonoid/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/carsonoid/subscriptions",
          "organizations_url": "https://api.github.com/users/carsonoid/orgs",
          "repos_url": "https://api.github.com/users/carsonoid/repos",
          "events_url": "https://api.github.com/users/carsonoid/events{/privacy}",
          "received_events_url": "https://api.github.com/users/carsonoid/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "andydbc",
          "id": 31256170,
          "node_id": "MDQ6VXNlcjMxMjU2MTcw",
          "avatar_url": "https://avatars1.githubusercontent.com/u/31256170?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/andydbc",
          "html_url": "https://github.com/andydbc",
          "followers_url": "https://api.github.com/users/andydbc/followers",
          "following_url": "https://api.github.com/users/andydbc/following{/other_user}",
          "gists_url": "https://api.github.com/users/andydbc/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/andydbc/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/andydbc/subscriptions",
          "organizations_url": "https://api.github.com/users/andydbc/orgs",
          "repos_url": "https://api.github.com/users/andydbc/repos",
          "events_url": "https://api.github.com/users/andydbc/events{/privacy}",
          "received_events_url": "https://api.github.com/users/andydbc/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "machinaut",
          "id": 79779,
          "node_id": "MDQ6VXNlcjc5Nzc5",
          "avatar_url": "https://avatars3.githubusercontent.com/u/79779?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/machinaut",
          "html_url": "https://github.com/machinaut",
          "followers_url": "https://api.github.com/users/machinaut/followers",
          "following_url": "https://api.github.com/users/machinaut/following{/other_user}",
          "gists_url": "https://api.github.com/users/machinaut/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/machinaut/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/machinaut/subscriptions",
          "organizations_url": "https://api.github.com/users/machinaut/orgs",
          "repos_url": "https://api.github.com/users/machinaut/repos",
          "events_url": "https://api.github.com/users/machinaut/events{/privacy}",
          "received_events_url": "https://api.github.com/users/machinaut/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "abinoda",
          "id": 50083,
          "node_id": "MDQ6VXNlcjUwMDgz",
          "avatar_url": "https://avatars0.githubusercontent.com/u/50083?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/abinoda",
          "html_url": "https://github.com/abinoda",
          "followers_url": "https://api.github.com/users/abinoda/followers",
          "following_url": "https://api.github.com/users/abinoda/following{/other_user}",
          "gists_url": "https://api.github.com/users/abinoda/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/abinoda/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/abinoda/subscriptions",
          "organizations_url": "https://api.github.com/users/abinoda/orgs",
          "repos_url": "https://api.github.com/users/abinoda/repos",
          "events_url": "https://api.github.com/users/abinoda/events{/privacy}",
          "received_events_url": "https://api.github.com/users/abinoda/received_events",
          "type": "User",
          "site_admin": true,
          "score": 1.0
        },
        {
          "login": "noidontdig",
          "id": 1229810,
          "node_id": "MDQ6VXNlcjEyMjk4MTA=",
          "avatar_url": "https://avatars1.githubusercontent.com/u/1229810?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/noidontdig",
          "html_url": "https://github.com/noidontdig",
          "followers_url": "https://api.github.com/users/noidontdig/followers",
          "following_url": "https://api.github.com/users/noidontdig/following{/other_user}",
          "gists_url": "https://api.github.com/users/noidontdig/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/noidontdig/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/noidontdig/subscriptions",
          "organizations_url": "https://api.github.com/users/noidontdig/orgs",
          "repos_url": "https://api.github.com/users/noidontdig/repos",
          "events_url": "https://api.github.com/users/noidontdig/events{/privacy}",
          "received_events_url": "https://api.github.com/users/noidontdig/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "austinkelleher",
          "id": 3771924,
          "node_id": "MDQ6VXNlcjM3NzE5MjQ=",
          "avatar_url": "https://avatars0.githubusercontent.com/u/3771924?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/austinkelleher",
          "html_url": "https://github.com/austinkelleher",
          "followers_url": "https://api.github.com/users/austinkelleher/followers",
          "following_url": "https://api.github.com/users/austinkelleher/following{/other_user}",
          "gists_url": "https://api.github.com/users/austinkelleher/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/austinkelleher/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/austinkelleher/subscriptions",
          "organizations_url": "https://api.github.com/users/austinkelleher/orgs",
          "repos_url": "https://api.github.com/users/austinkelleher/repos",
          "events_url": "https://api.github.com/users/austinkelleher/events{/privacy}",
          "received_events_url": "https://api.github.com/users/austinkelleher/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "liuwons",
          "id": 9864950,
          "node_id": "MDQ6VXNlcjk4NjQ5NTA=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/9864950?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/liuwons",
          "html_url": "https://github.com/liuwons",
          "followers_url": "https://api.github.com/users/liuwons/followers",
          "following_url": "https://api.github.com/users/liuwons/following{/other_user}",
          "gists_url": "https://api.github.com/users/liuwons/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/liuwons/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/liuwons/subscriptions",
          "organizations_url": "https://api.github.com/users/liuwons/orgs",
          "repos_url": "https://api.github.com/users/liuwons/repos",
          "events_url": "https://api.github.com/users/liuwons/events{/privacy}",
          "received_events_url": "https://api.github.com/users/liuwons/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "Alwahsh",
          "id": 3496597,
          "node_id": "MDQ6VXNlcjM0OTY1OTc=",
          "avatar_url": "https://avatars3.githubusercontent.com/u/3496597?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Alwahsh",
          "html_url": "https://github.com/Alwahsh",
          "followers_url": "https://api.github.com/users/Alwahsh/followers",
          "following_url": "https://api.github.com/users/Alwahsh/following{/other_user}",
          "gists_url": "https://api.github.com/users/Alwahsh/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Alwahsh/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Alwahsh/subscriptions",
          "organizations_url": "https://api.github.com/users/Alwahsh/orgs",
          "repos_url": "https://api.github.com/users/Alwahsh/repos",
          "events_url": "https://api.github.com/users/Alwahsh/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Alwahsh/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "antiface",
          "id": 1619852,
          "node_id": "MDQ6VXNlcjE2MTk4NTI=",
          "avatar_url": "https://avatars0.githubusercontent.com/u/1619852?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/antiface",
          "html_url": "https://github.com/antiface",
          "followers_url": "https://api.github.com/users/antiface/followers",
          "following_url": "https://api.github.com/users/antiface/following{/other_user}",
          "gists_url": "https://api.github.com/users/antiface/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/antiface/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/antiface/subscriptions",
          "organizations_url": "https://api.github.com/users/antiface/orgs",
          "repos_url": "https://api.github.com/users/antiface/repos",
          "events_url": "https://api.github.com/users/antiface/events{/privacy}",
          "received_events_url": "https://api.github.com/users/antiface/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        },
        {
          "login": "aQuaYi",
          "id": 6028869,
          "node_id": "MDQ6VXNlcjYwMjg4Njk=",
          "avatar_url": "https://avatars0.githubusercontent.com/u/6028869?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/aQuaYi",
          "html_url": "https://github.com/aQuaYi",
          "followers_url": "https://api.github.com/users/aQuaYi/followers",
          "following_url": "https://api.github.com/users/aQuaYi/following{/other_user}",
          "gists_url": "https://api.github.com/users/aQuaYi/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/aQuaYi/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/aQuaYi/subscriptions",
          "organizations_url": "https://api.github.com/users/aQuaYi/orgs",
          "repos_url": "https://api.github.com/users/aQuaYi/repos",
          "events_url": "https://api.github.com/users/aQuaYi/events{/privacy}",
          "received_events_url": "https://api.github.com/users/aQuaYi/received_events",
          "type": "User",
          "site_admin": false,
          "score": 1.0
        }
      ]
    }
    """
}
